language: groovy
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
before_install:
  chmod +x gradlew
env:
  global:

deploy:
#  - provider: script
#    skip_cleanup: true
#    script: ./gradlew artifactoryPublish -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY}
#    on:
#      branch: master
#      jdk: oraclejdk8
#  - provider: script
#    skip_cleanup: true
#    script: ./gradlew bintrayDeploy
#    on:
#      tags: true
#      jdk: oraclejdk8
